### ISSUE TITLE
banner duplication

### ISSUE THREAD

**Issue by Jesande** [spd-master-web/Rain---E-commerce-design#2]
For hypothesis #2
we create the banner and add the j query. 
https://github.com/spd-master-web/Rain-ABtesting/blob/master/solutions/banner.js
It works fine the first time but if the user clicks on the colors available, the code add one more banner each time. 

![Captura de Pantalla 2020-05-26 a la(s) 9 00 52 p  m](https://user-images.githubusercontent.com/58031707/82945537-65833180-9f9d-11ea-8312-ea6df4550215.png)

How can we fix this?

NOTE: https://www.ray-ban.com/usa/sunglasses/RB3857%20UNISEX%20008-frank%20legend%20gold-gold/8056597178518?category_Id=1939669 this is the current PDP

**Comment by gorazd** [comment]
You could use the `has` method to check for the contents of the element you are appending to.

https://api.jquery.com/has/
