### ISSUE TITLE
Change the text color in the main menu

### ISSUE THREAD

**Issue by Jesande** [spd-master-web/Rain---E-commerce-design#3]
Hi!
We are trying to change the color of the "promo" menu from the Rayban site (https://www.ray-ban.com/usa) to black but it's not working on js.
This is the link to our js file:
(https://github.com/spd-master-web/Rain---E-commerce-design/blob/master/solutions/promo.js
)

**Comment by Jesande** [comment]
@gorazd ?

**Comment by gorazd** [comment]
What if you try to remove the class that makes it red:
`$("[data-element-id='X_X_MainNav_Promo']").removeClass( "rb-red-fg" );`
